### ISSUE TITLE
Does this tool allow communicating between multiple Firebase databases?

### ISSUE THREAD

**Issue by tsemerad** [jamestalmage/firebase-copy#1]
I'm writing a tool that will copy most of my data in my production firebase db into a development db. 

I'd like to do something like this:

``` javascript
var firebaseCopy = require('firebase-copy');

var Firebase = require('firebase');
var Firebase1 = firebaseCopy();
var Firebase2 = firebaseCopy();

var refProd = new Firebase1('https://my-firebase-prod.firebaseio.com');
var refDev = new Firebase2('https://my-firebase-dev.firebaseio.com');
```

I'm assuming this library isn't useful for this, since the README states "This is useful for testing interactions of multiple clients from a single machine" but nothing about multiple databases. Am I correct in assuming this?

**Comment by jamestalmage** [comment]
You are correct. It creates additional copies of the firebase client. They do not share global state.

So Firebase.goOffline() only affects instances made with that copy.
